import { Prediction } from "@/lib/api";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft, AlertTriangle, TrendingUp } from "lucide-react";

interface ResultsViewProps {
  imageUrl: string;
  predictions: Prediction[];
  onReset: () => void;
}

const RANK_STYLES = [
  {
    badge: "bg-amber-500/15 text-amber-600 dark:text-amber-400 ring-1 ring-amber-500/20",
    bar: "from-amber-500 to-amber-400",
    label: "🥇",
  },
  {
    badge: "bg-slate-400/15 text-slate-500 dark:text-slate-400 ring-1 ring-slate-400/20",
    bar: "from-slate-400 to-slate-300",
    label: "🥈",
  },
  {
    badge: "bg-orange-600/15 text-orange-600 dark:text-orange-400 ring-1 ring-orange-500/20",
    bar: "from-orange-500 to-orange-400",
    label: "🥉",
  },
  {
    badge: "bg-primary/10 text-primary ring-1 ring-primary/20",
    bar: "from-primary to-primary/70",
    label: "4",
  },
  {
    badge: "bg-muted text-muted-foreground ring-1 ring-border",
    bar: "from-muted-foreground/40 to-muted-foreground/20",
    label: "5",
  },
];

export function ResultsView({
  imageUrl,
  predictions,
  onReset,
}: ResultsViewProps) {
  return (
    <div className="mx-auto w-full max-w-3xl space-y-8 animate-fade-in-up">
      <Button
        variant="ghost"
        onClick={onReset}
        className="gap-2 rounded-full hover:bg-primary/10"
      >
        <ArrowLeft className="h-4 w-4" /> Try Another Image
      </Button>

      <div className="grid gap-8 md:grid-cols-[280px_1fr]">
        {/* Image */}
        <div className="overflow-hidden rounded-2xl glass-card p-1.5">
          <img
            src={imageUrl}
            alt="Analyzed skin"
            className="h-auto w-full rounded-xl object-cover"
          />
        </div>

        {/* Predictions */}
        <div className="space-y-3">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp className="h-5 w-5 text-primary" />
            <h2 className="text-lg font-semibold text-foreground">
              Analysis Results
            </h2>
          </div>
          {predictions.map((p, i) => {
            const style = RANK_STYLES[i] || RANK_STYLES[4];
            return (
              <Card
                key={p.name}
                className="overflow-hidden border-border/50 transition-all duration-300 hover:shadow-md hover:border-primary/20"
                style={{
                  animation: `slide-in 0.4s ease-out ${i * 0.1}s forwards`,
                  opacity: 0,
                }}
              >
                <CardContent className="flex items-center gap-4 p-4">
                  <span
                    className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl text-sm font-bold ${style.badge}`}
                  >
                    {style.label}
                  </span>
                  <div className="min-w-0 flex-1">
                    <div className="flex items-baseline justify-between gap-2">
                      <p className="truncate font-medium text-foreground">
                        {p.name.replace(/_/g, " ")}
                      </p>
                      <span className="shrink-0 text-sm font-bold tabular-nums text-foreground">
                        {(p.confidence * 100).toFixed(1)}%
                      </span>
                    </div>
                    <div className="mt-2.5 h-2.5 overflow-hidden rounded-full bg-secondary">
                      <div
                        className={`h-full rounded-full bg-gradient-to-r ${style.bar} transition-all duration-1000 ease-out`}
                        style={{
                          width: `${p.confidence * 100}%`,
                          animation: `fade-in-up 0.6s ease-out ${i * 0.15}s forwards`,
                        }}
                      />
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>

      {/* Disclaimer */}
      <div className="flex items-start gap-3 rounded-2xl glass-card p-5 text-sm text-muted-foreground">
        <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-amber-500/10">
          <AlertTriangle className="h-4 w-4 text-amber-500" />
        </div>
        <p className="leading-relaxed">
          These results are generated by an AI model and are{" "}
          <strong className="text-foreground">not a medical diagnosis</strong>.
          Please consult a qualified dermatologist for professional evaluation.
        </p>
      </div>
    </div>
  );
}
